### ISSUE TITLE
clear but not delete option

### ISSUE THREAD

**Issue by Seluj78** [sanders41/pytest-meilisearch#89]
I would like to use your `meilisearch_clear_indexes` option but it deletes the index as well.

I think it should be renamed `meilisearch_delete_indexes` and you should add a new option to clear the indexes simply

**Comment by sanders41** [comment]
Is there an issue with deleting it instead? What I am worried about with this change is what does `meilisearch_clear_indexes` become? Does it just clear documents? Just clear settings? Clear both? What about the primary key, it can't be changed after it gets set, but clear implies it is. There seems like a lot of situations where this could get people into problems.

**Comment by Seluj78** [comment]
Well, because my code doesn't automatically recreates indexes when deleted, when I used your setting I got a bunch of errors :)

My idea was that `clear_indexes` just deletes all documents from existing indexes and that's it. I personally don't touch settings and primary keys :)

**Comment by Seluj78** [comment]
Yes that would work for me !

I won't have time tonight nor tomorrow I think, so if you can do it, I'll review the PR happily
